version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12

    working_directory: /go/src/github.com/kou64yama/takanawa

    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS

      - restore_cache:
          keys:
            - v1-pkg-cache

      - run: go get github.com/jstemmer/go-junit-report
      - run: go get github.com/golang/dep/cmd/dep
      - run: dep ensure

      - run:
          name: Run unit tests
          command: |
            trap "go-junit-report < ${TEST_RESULT}/go-test.out > ${TEST_RESULT}/go-test-report.xml" EXIT
            make test | tee ${TEST_RESULT}/go-test.out

      - run: make

      - save_cache:
          key: v1-pkg-cache
          paths:
            - /go/pkg

      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-results
